import sqlite3
import pandas as pd
from pathlib import Path

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import ParagraphStyle

# ---------------------------------------------------
# Project Paths
# ---------------------------------------------------

BASE_DIR = Path(__file__).resolve().parents[2]

DB_PATH = BASE_DIR / "nifty100.db"

OUTPUT_DIR = BASE_DIR / "output"

PORTFOLIO_DIR = OUTPUT_DIR / "reports" / "portfolio"

PORTFOLIO_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ---------------------------------------------------
# Database Connection
# ---------------------------------------------------

conn = sqlite3.connect(DB_PATH)

# ---------------------------------------------------
# Load Companies + Sector Information
# ---------------------------------------------------

companies = pd.read_sql("""

SELECT

c.id,

c.company_name,

s.broad_sector,

s.sub_sector,

s.market_cap_category

FROM companies c

LEFT JOIN sectors s

ON c.id=s.company_id

ORDER BY c.company_name

""", conn)

# ---------------------------------------------------
# Load Latest Financial Ratios
# ---------------------------------------------------

ratios = pd.read_sql("""

SELECT *

FROM financial_ratios fr

WHERE year=(

SELECT MAX(year)

FROM financial_ratios f2

WHERE f2.company_id=fr.company_id

)

""", conn)

# ---------------------------------------------------
# Merge
# ---------------------------------------------------

portfolio = companies.merge(

ratios,

left_on="id",

right_on="company_id",

how="left"

)

print("Companies Loaded :", len(portfolio))

# ---------------------------------------------------
# Styles
# ---------------------------------------------------

styles = getSampleStyleSheet()

title_style = ParagraphStyle(

"Title",

parent=styles["Title"],

alignment=TA_CENTER,

fontSize=22,

spaceAfter=20,

textColor=colors.darkblue

)

heading_style = ParagraphStyle(

"Heading",

parent=styles["Heading2"],

spaceAfter=8,

textColor=colors.darkblue

)

normal_style = styles["BodyText"]

# ---------------------------------------------------
# PDF Document
# ---------------------------------------------------

doc = SimpleDocTemplate(

str(

PORTFOLIO_DIR /

"portfolio_summary.pdf"

),

pagesize=A4

)

story = []

# =====================================================
# COVER PAGE
# =====================================================

story.append(

    Paragraph(
        "NIFTY 100 FINANCIAL INTELLIGENCE PLATFORM",
        title_style
    )

)

story.append(Spacer(1, 20))

story.append(

    Paragraph(

        "<b>Portfolio Summary Report</b>",

        heading_style

    )

)

story.append(Spacer(1, 12))

story.append(

    Paragraph(

        """
        This report provides a portfolio-wide summary of all companies
        included in the NIFTY 100 Financial Intelligence Platform.

        Each page contains:

        • Company Profile

        • Sector Information

        • Top Financial KPIs

        • Trend Indicators

        • Capital Allocation Metrics

        • Cash Flow Intelligence Summary
        """,

        normal_style

    )

)

story.append(Spacer(1, 20))

total_companies = len(portfolio)

total_sectors = portfolio["broad_sector"].nunique()

avg_roe = round(
    portfolio["return_on_equity_pct"].mean(),
    2
)

avg_roce = round(
    portfolio["return_on_capital_employed_pct"].mean(),
    2
)

avg_fcf = round(
    portfolio["free_cash_flow_cr"].mean(),
    2
)

summary_table = Table([

    ["Metric", "Value"],

    ["Companies", total_companies],

    ["Sectors", total_sectors],

    ["Average ROE", f"{avg_roe}%"],

    ["Average ROCE", f"{avg_roce}%"],

    ["Average Free Cash Flow", f"{avg_fcf} Cr"]

])

summary_table.setStyle([

    ("GRID",(0,0),(-1,-1),1,colors.grey),

    ("BACKGROUND",(0,0),(-1,0),colors.lightgrey),

    ("BACKGROUND",(0,1),(-1,-1),colors.whitesmoke),

    ("ALIGN",(0,0),(-1,-1),"CENTER"),

    ("BOTTOMPADDING",(0,0),(-1,-1),8)

])

story.append(summary_table)

story.append(Spacer(1,25))

story.append(

    Paragraph(

        "<b>Generated by:</b> Likitha R",

        normal_style

    )

)

story.append(

    Paragraph(

        "Bluestock Fintech Internship Project",

        normal_style

    )

)

story.append(

    Paragraph(

        "NIFTY 100 Financial Intelligence Platform",

        normal_style

    )

)

story.append(PageBreak())

# =====================================================
# TREND ARROW
# =====================================================

def trend_arrow(current, previous):

    if pd.isna(current) or pd.isna(previous):

        return "N/A"

    if previous == 0:

        return "→"

    change = (

        (current - previous)

        /

        abs(previous)

    ) * 100

    if change > 2:

        return "↑"

    elif change < -2:

        return "↓"

    else:

        return "→"
    
def fmt(value, suffix=""):

    if pd.isna(value):

        return "N/A"

    if isinstance(value, float):

        return f"{value:.2f}{suffix}"

    return f"{value}{suffix}"

def company_history(company):

    return pd.read_sql(

        f"""

        SELECT *

        FROM financial_ratios

        WHERE company_id='{company}'

        ORDER BY year

        """,

        conn

    )

# =====================================================
# COMPANY PAGES
# =====================================================

for company in portfolio.itertuples():

    history = company_history(company.id)

    if len(history) < 2:
        continue

    latest = history.iloc[-1]
    previous = history.iloc[-2]

    # --------------------------------------------
    # Trend Arrows
    # --------------------------------------------

    roe_arrow = trend_arrow(
        latest["return_on_equity_pct"],
        previous["return_on_equity_pct"]
    )

    roce_arrow = trend_arrow(
        latest["return_on_capital_employed_pct"],
        previous["return_on_capital_employed_pct"]
    )

    sales_arrow = trend_arrow(
        latest["sales"],
        previous["sales"]
    )

    fcf_arrow = trend_arrow(
        latest["free_cash_flow_cr"],
        previous["free_cash_flow_cr"]
    )

    # --------------------------------------------
    # Company Title
    # --------------------------------------------

    story.append(

        Paragraph(

            f"<b>{company.company_name}</b>",

            title_style

        )

    )

    story.append(Spacer(1,8))

    # --------------------------------------------
    # Company Information
    # --------------------------------------------

    info_table = Table([

        ["Company ID", company.id],

        ["Sector", company.broad_sector],

        ["Sub Sector", company.sub_sector],

        ["Market Cap", company.market_cap_category]

    ])

    info_table.setStyle([

        ("GRID",(0,0),(-1,-1),0.5,colors.grey),

        ("BACKGROUND",(0,0),(0,-1),colors.lightgrey),

        ("BOTTOMPADDING",(0,0),(-1,-1),6),

        ("FONTSIZE",(0,0),(-1,-1),9)

    ])

    story.append(info_table)

    story.append(Spacer(1,12))

    # --------------------------------------------
    # KPI Table
    # --------------------------------------------

    kpi_table = Table([

        ["Metric","Value","Trend"],

        [

            "ROE",

            fmt(latest["return_on_equity_pct"],"%"),

            roe_arrow

        ],

        [

            "ROCE",

            fmt(latest["return_on_capital_employed_pct"],"%"),

            roce_arrow

        ],

        [

            "Revenue",

            fmt(latest["sales"]," Cr"),

            sales_arrow

        ],

        [

            "Free Cash Flow",

            fmt(latest["free_cash_flow_cr"]," Cr"),

            fcf_arrow

        ],

        [

            "Debt / Equity",

            fmt(latest["debt_to_equity"]),

            "-"

        ],

        [

            "CFO Quality",

            fmt(latest["cfo_quality_score"]),

            "-"

        ]

    ])

    kpi_table.setStyle([

        ("GRID",(0,0),(-1,-1),0.5,colors.grey),

        ("BACKGROUND",(0,0),(-1,0),colors.darkblue),

        ("TEXTCOLOR",(0,0),(-1,0),colors.white),

        ("BACKGROUND",(0,1),(-1,-1),colors.whitesmoke),

        ("ALIGN",(0,0),(-1,-1),"CENTER"),

        ("BOTTOMPADDING",(0,0),(-1,-1),8),

        ("FONTSIZE",(0,0),(-1,-1),9)

    ])

    story.append(kpi_table)

    story.append(Spacer(1,15))

# --------------------------------------------
# Financial Health Summary
# --------------------------------------------

health = []

if latest["return_on_equity_pct"] >= 20:
    health.append("• Strong shareholder returns")

if latest["return_on_capital_employed_pct"] >= 20:
    health.append("• Efficient capital allocation")

if latest["debt_to_equity"] <= 1:
    health.append("• Conservative leverage")

if latest["free_cash_flow_cr"] > 0:
    health.append("• Positive Free Cash Flow")

if latest["cfo_quality_score"] >= 1:
    health.append("• High-quality operating cash flow")

if len(health) == 0:
    health.append("• Financial performance requires monitoring")

story.append(
    Paragraph(
        "<b>Financial Health Summary</b>",
        heading_style
    )
)

for item in health:

    story.append(
        Paragraph(
            item,
            normal_style
        )
    )

story.append(Spacer(1,12))

story.append(PageBreak())

# =====================================================
# REMOVE LAST BLANK PAGE
# =====================================================

if len(story) > 0 and isinstance(story[-1], PageBreak):
    story.pop()

# =====================================================
# FOOTER
# =====================================================

def footer(canvas, doc):

    canvas.saveState()

    canvas.setFont("Helvetica", 8)

    canvas.drawString(
        40,
        20,
        "NIFTY 100 Financial Intelligence Platform | Portfolio Summary"
    )

    canvas.drawRightString(
        550,
        20,
        f"Page {canvas.getPageNumber()}"
    )

    canvas.restoreState()


# =====================================================
# BUILD PDF
# =====================================================

doc.build(
    story,
    onFirstPage=footer,
    onLaterPages=footer
)

# =====================================================
# CLOSE DATABASE
# =====================================================

conn.close()

# =====================================================
# SUMMARY
# =====================================================

print("\n" + "=" * 60)
print("PORTFOLIO SUMMARY REPORT GENERATED")
print("=" * 60)

print(f"Companies Included : {len(portfolio)}")
print(f"Sectors Covered    : {portfolio['broad_sector'].nunique()}")

print(
    "\nOutput File :",
    PORTFOLIO_DIR / "portfolio_summary.pdf"
)

print("\nGeneration Completed Successfully.")
print("=" * 60)